version: "3.8"

services:
  database:
    container_name: "postgres-burocrasym"
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password